kind: Service
apiVersion: v1
metadata:
  name: nginx-service-for-html
  namespace: nginx
spec:
  selector:
    app: nginx-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP