apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-app-ns
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: 381492063209.dkr.ecr.ap-south-1.amazonaws.com/flaskproj_dev_ecr:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysql-headless.flask-app-ns.svc.cluster.local"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      imagePullSecrets:
        - name: ecr-regcred
