apiVersion: v1
kind: Service
metadata:
  name: my-dotnet-service
  namespace: my-dotnet-app
spec:
  type: NodePort
  selector:
    app: my-dotnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  